language: php

php:
  - 5.6
  - 5.5
  - hhvm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7677260d9dfcddc643ff
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - composer install

script:
#  - ./vendor/bin/phpspec run
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml